/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package keretaapi;


import java.awt.Color;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
/**
 *
 * @author Dewa
 */
public class LoginAdmin extends javax.swing.JFrame {
    /**
     * Creates new form LoginAdmin
     */
    public LoginAdmin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_title = new javax.swing.JLabel();
        jLabel_Username = new javax.swing.JLabel();
        jLabel_Password = new javax.swing.JLabel();
        jTextField_UsernameAdmin = new javax.swing.JTextField();
        jPasswordField_Admin = new javax.swing.JPasswordField();
        jButton_LoginAdmin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel_backAdmin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_title.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel_title.setText("LOGIN Admin ");

        jLabel_Username.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel_Username.setText("Username");

        jLabel_Password.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel_Password.setText("Password");

        jTextField_UsernameAdmin.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jTextField_UsernameAdmin.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_UsernameAdmin.setText("Halosaya");
        jTextField_UsernameAdmin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_UsernameAdminFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_UsernameAdminFocusLost(evt);
            }
        });

        jPasswordField_Admin.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jPasswordField_Admin.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField_Admin.setText("password");
        jPasswordField_Admin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField_AdminFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField_AdminFocusLost(evt);
            }
        });

        jButton_LoginAdmin.setText("Masuk");
        jButton_LoginAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LoginAdminActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel4.setText(" ");

        jLabel_backAdmin.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel_backAdmin.setText("<kembali");
        jLabel_backAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_backAdminMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Poppins ExtraBold", 1, 18)); // NOI18N
        jLabel1.setText(" X ");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel_backAdmin))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel_Username)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_UsernameAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel_Password)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton_LoginAdmin)
                                    .addComponent(jPasswordField_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_title)
                        .addGap(86, 86, 86))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(jLabel_title)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Username)
                    .addComponent(jTextField_UsernameAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Password)
                    .addComponent(jPasswordField_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(57, 57, 57)
                .addComponent(jButton_LoginAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(jLabel_backAdmin)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_LoginAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LoginAdminActionPerformed
        
        PreparedStatement st;
        ResultSet rs;
        
        //Menerima input 
        String UsernameA = jTextField_UsernameAdmin.getText();
        String PasswordA = String.valueOf(jPasswordField_Admin.getPassword());
        // mengambil data dari database
        String query = "SELECT * FROM `data_admin` WHERE `UsernameA` = ? AND `PasswordA` = ?";
        
        try {
            st = DBConnection.getConnection().prepareStatement(query);
            
            st.setString(1, UsernameA);
            st.setString(2, PasswordA);
        
            rs = st.executeQuery();
            // jika benar pindah ke halaman Laporan
            if(rs.next()){
                Agents Agn = new Agents();
                Agn.setVisible(true);
                Agn.pack();
                Agn.setLocationRelativeTo(null);
                this.dispose();
            }// jika salah
            else JOptionPane.showMessageDialog(null, "Invalid username and password");
        } catch (SQLException ex) {
            Logger.getLogger(LoginAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton_LoginAdminActionPerformed

// Menghapus tulisan hint pada kolom username
    private void jTextField_UsernameAdminFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_UsernameAdminFocusGained
        if (jTextField_UsernameAdmin.getText().trim().equals("Halosaya")){
           jTextField_UsernameAdmin.setText("");
           jTextField_UsernameAdmin.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTextField_UsernameAdminFocusGained
// menampilkan tulisan hint pada kolom username bila belum ada input
    private void jTextField_UsernameAdminFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_UsernameAdminFocusLost
        if(jTextField_UsernameAdmin.getText().trim().equals("")||
           jTextField_UsernameAdmin.getText().trim().equals("Halosaya")){
                jTextField_UsernameAdmin.setText("Halosaya");
                jTextField_UsernameAdmin.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jTextField_UsernameAdminFocusLost

// Menghapus tulisan hint pada kolom username
    private void jPasswordField_AdminFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_AdminFocusGained
        if (jPasswordField_Admin.getText().trim().equals("password")){
            jPasswordField_Admin.setText("");
            jPasswordField_Admin.setForeground(Color.black);
        }
    }//GEN-LAST:event_jPasswordField_AdminFocusGained
// menampilkan tulisan hint pada kolom username bila belum ada input
    private void jPasswordField_AdminFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_AdminFocusLost
        if (jPasswordField_Admin.getText().trim().equals("")||
            jPasswordField_Admin.getText().trim().equals("password")){
                jPasswordField_Admin.setText("password");
                jPasswordField_Admin.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jPasswordField_AdminFocusLost

// kembali ke halaman pertama
    private void jLabel_backAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_backAdminMouseClicked
        WelcomingPage Wp = new WelcomingPage();
        Wp.setVisible(true);
        Wp.pack();
        Wp.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel_backAdminMouseClicked

// menggganti warna border ketika mouse masuk
    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        Border label_border = BorderFactory.createMatteBorder(1,1,1,1, Color.white);
        jLabel1.setBorder(label_border);
        jLabel1.setForeground(Color.white);
    }//GEN-LAST:event_jLabel1MouseEntered
// menggganti warna border ketika mouse keluar
    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        Border label_border = BorderFactory.createMatteBorder(1,1,1,1, Color.black);
        jLabel1.setBorder(label_border);
        jLabel1.setForeground(Color.black);
    }//GEN-LAST:event_jLabel1MouseExited
// keluar program
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_LoginAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_Password;
    private javax.swing.JLabel jLabel_Username;
    private javax.swing.JLabel jLabel_backAdmin;
    private javax.swing.JLabel jLabel_title;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField_Admin;
    private javax.swing.JTextField jTextField_UsernameAdmin;
    // End of variables declaration//GEN-END:variables
}
