/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package keretaapi;

import java.awt.Color;
import javax.swing.ButtonGroup;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author Dewa
 */
public class RegistrasiPenumpang extends javax.swing.JFrame {
    
    public RegistrasiPenumpang() {
        initComponents();
        this.setLocationRelativeTo(null);
       
        ButtonGroup BG = new ButtonGroup();
        BG.add(jRadioButton_Male);
        BG.add(jRadioButton_Female);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_TitleRegistrasi = new javax.swing.JLabel();
        jLabel_FullName = new javax.swing.JLabel();
        jLabel_Username = new javax.swing.JLabel();
        jLabel_Email = new javax.swing.JLabel();
        jTextField_Email = new javax.swing.JTextField();
        jTextField_FullName = new javax.swing.JTextField();
        jLabelPassword = new javax.swing.JLabel();
        jTextField_Username = new javax.swing.JTextField();
        jPasswordField = new javax.swing.JPasswordField();
        jButton_Regist = new javax.swing.JButton();
        jRadioButton_Male = new javax.swing.JRadioButton();
        jRadioButton_Female = new javax.swing.JRadioButton();
        jLabel_Gender = new javax.swing.JLabel();
        jLabel_Date = new javax.swing.JLabel();
        jLabel_Back = new javax.swing.JLabel();
        jLabel_Telp = new javax.swing.JLabel();
        jFormattedTextField_Date = new javax.swing.JFormattedTextField();
        jTextField_Telp = new javax.swing.JTextField();
        jError = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_TitleRegistrasi.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel_TitleRegistrasi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_TitleRegistrasi.setText("Registrasi");

        jLabel_FullName.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel_FullName.setText("Nama Lengkap");

        jLabel_Username.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel_Username.setText("Username");

        jLabel_Email.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel_Email.setText("Email");

        jTextField_Email.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jTextField_Email.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_Email.setText("filipus@binus.ac.id");
        jTextField_Email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_EmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_EmailFocusLost(evt);
            }
        });

        jTextField_FullName.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jTextField_FullName.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_FullName.setText("Filipus Sadewa");
        jTextField_FullName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_FullNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_FullNameFocusLost(evt);
            }
        });

        jLabelPassword.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabelPassword.setText("Password");

        jTextField_Username.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jTextField_Username.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_Username.setText("sukalupa");
        jTextField_Username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_UsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_UsernameFocusLost(evt);
            }
        });

        jPasswordField.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jPasswordField.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField.setText("password");
        jPasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordFieldFocusLost(evt);
            }
        });

        jButton_Regist.setText("Daftar");
        jButton_Regist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RegistActionPerformed(evt);
            }
        });

        jRadioButton_Male.setSelected(true);
        jRadioButton_Male.setText("Laki - laki");
        jRadioButton_Male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_MaleActionPerformed(evt);
            }
        });

        jRadioButton_Female.setText("Perempuan");
        jRadioButton_Female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_FemaleActionPerformed(evt);
            }
        });

        jLabel_Gender.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel_Gender.setText("Jenis Kelamin");

        jLabel_Date.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel_Date.setText("Tanggal Lahir");

        jLabel_Back.setText("<kembali");
        jLabel_Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_BackMouseClicked(evt);
            }
        });

        jLabel_Telp.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel_Telp.setText("No Telp.");

        jFormattedTextField_Date.setForeground(new java.awt.Color(153, 153, 153));
        jFormattedTextField_Date.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.LONG))));
        jFormattedTextField_Date.setText("June 17, 2022");
        jFormattedTextField_Date.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFormattedTextField_DateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextField_DateFocusLost(evt);
            }
        });

        jTextField_Telp.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jTextField_Telp.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_Telp.setText("089123456789");
        jTextField_Telp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_TelpFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_TelpFocusLost(evt);
            }
        });
        jTextField_Telp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_TelpKeyTyped(evt);
            }
        });

        jError.setText(" ");

        jLabel1.setFont(new java.awt.Font("Poppins ExtraBold", 1, 18)); // NOI18N
        jLabel1.setText(" X ");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Regist)
                .addGap(122, 122, 122))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jError, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_Email)
                                    .addComponent(jLabel_Gender)
                                    .addComponent(jLabel_Date)
                                    .addComponent(jLabel_Telp))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jRadioButton_Male)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButton_Female))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(jTextField_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField_Telp, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jFormattedTextField_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_Username)
                                    .addComponent(jLabelPassword)
                                    .addComponent(jLabel_FullName))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_FullName, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPasswordField, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTextField_Username, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(2, 2, 2)))
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_TitleRegistrasi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addComponent(jLabel_TitleRegistrasi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Username)
                    .addComponent(jTextField_Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPassword)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_FullName)
                    .addComponent(jTextField_FullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Email))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton_Male)
                    .addComponent(jLabel_Gender)
                    .addComponent(jRadioButton_Female))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Date)
                    .addComponent(jFormattedTextField_Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Telp)
                    .addComponent(jTextField_Telp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jButton_Regist)
                .addGap(34, 34, 34)
                .addComponent(jLabel_Back)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
// tidak terpakai
    private void jRadioButton_MaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_MaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_MaleActionPerformed

    private void jRadioButton_FemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_FemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_FemaleActionPerformed

    
//submit registrasi
    private void jButton_RegistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegistActionPerformed
        //Getter -> menerima hasil input
        String NamaP = jTextField_FullName.getText();
        String UsernameP = jTextField_Username.getText();
        String EmailP = jTextField_Email.getText();
        String PasswordP =  String.valueOf(jPasswordField.getPassword());
        String Gender = "Laki-laki";
        if (jRadioButton_Female.isSelected()) Gender = "Female";
        String Telp = jTextField_Telp.getText();
       
        if (cekKolom()){
            if (!CheckUsername(UsernameP)){
                PreparedStatement ps;
                ResultSet rs;
                
                // menginputkan Data ke dalam Database
                String Regist_query = "INSERT INTO `data_penumpang`(`UsernameP`, `PasswordP`, `NamaLengkapP`, `EmailP`, `JenisKelamin`, `Telp`) VALUES (?,?,?,?,?,?)";    
            
                try {
                    ps = DBConnection.getConnection().prepareStatement(Regist_query);
                    ps.setString(1, UsernameP);
                    ps.setString(2, PasswordP);
                    ps.setString(3, NamaP);
                    ps.setString(4, EmailP);
                    ps.setString(5, Gender);
                    ps.setString(6, Telp);
                //jika berhasil
                if (ps.executeUpdate() != 0)
                    JOptionPane.showMessageDialog(null, "Berhasil! Silahkan kembali ke Login");
                //jika gagal
                else JOptionPane.showMessageDialog(null, "yah pembuatan akun Gagal :("); 

                } catch (SQLException ex) {
                    Logger.getLogger(RegistrasiPenumpang.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jButton_RegistActionPerformed

//Kembali ke halaman Login
    private void jLabel_BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_BackMouseClicked
        LoginPenumpang Lp = new LoginPenumpang();
        Lp.setVisible(true);
        Lp.pack();
        Lp.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel_BackMouseClicked

// menghapus tulisan hint pada Tanggal Lahir
    private void jFormattedTextField_DateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextField_DateFocusGained
        if (jFormattedTextField_Date.getText().trim().equals("June 17, 2022")){
           jFormattedTextField_Date.setText("");
           jFormattedTextField_Date.setForeground(Color.black);
        }
    }//GEN-LAST:event_jFormattedTextField_DateFocusGained
// Menampilkan Tulisan hint pada Tanggal Lahir
    private void jFormattedTextField_DateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextField_DateFocusLost
        if (jFormattedTextField_Date.getText().trim().equals("")||
            jFormattedTextField_Date.getText().trim().equals("June 17, 2022")){
                jFormattedTextField_Date.setText("June 17, 2022");
                jFormattedTextField_Date.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jFormattedTextField_DateFocusLost

// menghapus tulisan hint pada Nama Lengkap
    private void jTextField_FullNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_FullNameFocusGained
        if (jTextField_FullName.getText().trim().equals("Filipus Sadewa")){
            jTextField_FullName.setText("");
            jTextField_FullName.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTextField_FullNameFocusGained
// Menampilkan Tulisan hint pada Nama Lengkap
    private void jTextField_FullNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_FullNameFocusLost
        if (jTextField_FullName.getText().trim().equals("")||
            jTextField_FullName.getText().trim().equals("Filipus Sadewa")){
                jTextField_FullName.setText("Filipus Sadewa");
                jTextField_FullName.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jTextField_FullNameFocusLost

// menghapus tulisan hint pada Username
    private void jTextField_UsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_UsernameFocusGained
        if (jTextField_Username.getText().trim().equals("sukalupa")){
            jTextField_Username.setText("");
            jTextField_Username.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTextField_UsernameFocusGained
// Menampilkan Tulisan hint pada Username
    private void jTextField_UsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_UsernameFocusLost
        if(jTextField_Username.getText().trim().equals("")||
           jTextField_Username.getText().trim().equals("sukalupa")){
                jTextField_Username.setText("sukalupa");
                jTextField_Username.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jTextField_UsernameFocusLost

// menghapus tulisan hint pada Password
    private void jPasswordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldFocusGained
        if (jPasswordField.getText().trim().equals("password")){
            jPasswordField.setText("");
            jPasswordField.setForeground(Color.black);
        }
    }//GEN-LAST:event_jPasswordFieldFocusGained
// Menampilkan Tulisan hint pada Password
    private void jPasswordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldFocusLost
        if (jPasswordField.getText().trim().equals("")||
            jPasswordField.getText().trim().equals("password")){
                jPasswordField.setText("password");
                jPasswordField.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jPasswordFieldFocusLost

// menghapus tulisan hint pada Email
    private void jTextField_EmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_EmailFocusGained
        if (jTextField_Email.getText().trim().equals("filipus@binus.ac.id")){
            jTextField_Email.setText("");
            jTextField_Email.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTextField_EmailFocusGained
// Menampilkan Tulisan hint pada Email
    private void jTextField_EmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_EmailFocusLost
        if (jTextField_Email.getText().trim().equals("")||
            jTextField_Email.getText().trim().equals("filipus@binus.ac.id")){
                jTextField_Email.setText("filipus@binus.ac.id");
                jTextField_Email.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jTextField_EmailFocusLost

// Menghapus tulisan hint pada Telp    
    private void jTextField_TelpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_TelpFocusGained
        if (jTextField_Telp.getText().trim().equals("089123456789")){
            jTextField_Telp.setText("");
            jTextField_Telp.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTextField_TelpFocusGained
// Menampilkan tulisan hint pada Telp
    private void jTextField_TelpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_TelpFocusLost
        if (jTextField_Telp.getText().trim().equals("")||
            jTextField_Telp.getText().trim().equals("089123456789")){
                jTextField_Telp.setText("089123456789");
                jTextField_Telp.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jTextField_TelpFocusLost
// Melarang Input huruf pada Telp
    private void jTextField_TelpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_TelpKeyTyped
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_TelpKeyTyped

// mengganti warna border ketika mouse masuk
    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        Border label_border = BorderFactory.createMatteBorder(1,1,1,1, Color.white);
        jLabel1.setBorder(label_border);
        jLabel1.setForeground(Color.white);
    }//GEN-LAST:event_jLabel1MouseEntered
// mengganti warna border ketika mouse keluar
    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        Border label_border = BorderFactory.createMatteBorder(1,1,1,1, Color.black);
        jLabel1.setBorder(label_border);
        jLabel1.setForeground(Color.black);
    }//GEN-LAST:event_jLabel1MouseExited
// keluar program
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
       System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

// cek Kesamaan Username
    public boolean CheckUsername (String UsernameP){
        PreparedStatement st;
        ResultSet rs;
        
        boolean User_sama = false;
        
        String query = "SELECT * FROM `data_penumpang` WHERE `UsernameP` = ?";
        
        try {
            st = DBConnection.getConnection().prepareStatement(query);
            st.setString(1, UsernameP);
            rs = st.executeQuery();
            // jika username sama
            if (rs.next()){
                User_sama = true;
                jError.setText("Username Already Taken!");
                jError.setForeground(Color.red);
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(RegistrasiPenumpang.class.getName()).log(Level.SEVERE, null, ex);
        }
        return User_sama;
    }

// cek kolom kosong
    public boolean cekKolom(){
        String Usname = jTextField_Username.getText();
        String Pass = String.valueOf(jPasswordField.getPassword());
        String NLengkap = jTextField_Username.getText();
        String Eml = jTextField_Email.getText();
        String Tgl = jFormattedTextField_Date.getText();
        String Tlp = jTextField_Telp.getText();
        
        if (Usname.trim().equals("")||Pass.trim().equals("")||NLengkap.trim().equals("")||Eml.trim().equals("")
            ||Tgl.trim().equals("")||Tlp.trim().equals("")){
            JOptionPane.showMessageDialog(null,"Kotak tidak boleh kosong");
            return false;
        }
    return true;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrasiPenumpang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrasiPenumpang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrasiPenumpang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrasiPenumpang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrasiPenumpang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Regist;
    private javax.swing.JLabel jError;
    private javax.swing.JFormattedTextField jFormattedTextField_Date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabel_Back;
    private javax.swing.JLabel jLabel_Date;
    private javax.swing.JLabel jLabel_Email;
    private javax.swing.JLabel jLabel_FullName;
    private javax.swing.JLabel jLabel_Gender;
    private javax.swing.JLabel jLabel_Telp;
    private javax.swing.JLabel jLabel_TitleRegistrasi;
    private javax.swing.JLabel jLabel_Username;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JRadioButton jRadioButton_Female;
    private javax.swing.JRadioButton jRadioButton_Male;
    private javax.swing.JTextField jTextField_Email;
    private javax.swing.JTextField jTextField_FullName;
    private javax.swing.JTextField jTextField_Telp;
    private javax.swing.JTextField jTextField_Username;
    // End of variables declaration//GEN-END:variables
}
